### ISSUE TITLE
Storyboards annotations

### ISSUE THREAD

**Issue by anantha13** [kaydee8-1/GP2#5]
the storyboards should have annotations around it that explain what the different buttons do and where they take you to. Also comments on where popups will appear such as when an incorrect login is done.

**Comment by papazeke** [comment]
oh, and there should also be a heading above it to show which storyboard it is. So storyboard 1 prelogin, storyboard 2 postlogin etc...

**Comment by shristigurung** [comment]
In my design of the main page, I've added labels/annotations of the drop down bar as well as placing the buttons in a navigation bar for user ease.

**Comment by shristigurung** [comment]
the logo and the search bar are the only attributes within that level. 
the buttons i have moved down so all of them are in one place as well as adding annotations where i plan to have mouse hover features.
